import google.appengine.ext.ndb as ndb
from dcf.models import ModelWithAutogeneratedId, ModelWithComputedId


class Transacao(ModelWithComputedId):
    idConta = ndb.StringProperty(indexed=True)
    idDispositivo = ndb.StringProperty(indexed=True)
    data = ndb.DateProperty(indexed=True)
    valor = ndb.FloatProperty(indexed=True)
    ehFraude = ndb.BooleanProperty(indexed=True)
    latitude = ndb.FloatProperty(indexed=True)
    longitude = ndb.FloatProperty(indexed=True)


class Dispositivo(ModelWithComputedId):
    idConta = ndb.StringProperty(indexed=True)
    tipo = ndb.StringProperty(indexed=True)


class Conta(ModelWithComputedId):
    nome = ndb.StringProperty(indexed=True)


class Pessoa(ModelWithAutogeneratedId):
    nome = ndb.StringProperty(indexed=True)
    idade = ndb.IntegerProperty(indexed=True)
