application: dcf-ces63
version: alpha
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /.*
  script: main.app

libraries:
- name: markupsafe
  version: "0.15"

- name: jinja2
  version: "2.6"

builtins:
- remote_api: on
